# Generated by Django 3.2.18 on 2023-03-06 15:13

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000)),
                ('use_category', models.CharField(choices=[('medicinal', 'medicinal'), ('baking', 'baking'), ('cooking', 'cooking')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bookmark', models.ManyToManyField(blank='True', related_name='bookmark', to=settings.AUTH_USER_MODEL)),
                ('type_category', models.ManyToManyField(blank='True', related_name='type', to='blog.TypeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('spice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.spice')),
            ],
        ),
    ]
