# Generated by Django 3.2.18 on 2023-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
